name: Test PyBoulder
run-name: ${{ github.actor }} is testing ğŸ§ª PyBoulder ğŸ’»

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pyboulder-pytests:
    name: PyBoulder Pytests ğŸ§ª
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout Code ğŸ’»
        uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }} ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies ğŸ“š
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run PyBoulder Pytests ğŸƒ
        run: |
          pytest --cov=pyboulder --cov-report=xml
      - name: Upload Coverage Reports To Codecov ğŸ“¡
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
